export const SET_USERNAME = 'SET_USERNAME'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_USER_IS_PREMIUM = 'SET_USER_PREMIUM'

export const SET_USER_DAMAGE = 'SET_USER_DAMAGE';
export const SET_USER_ENERGY = 'SET_USER_ENERGY';
export const SET_USER_MAX_ENERGY = 'SET_USER_MAX_ENERGY';
export const SET_USER_BALANCE = 'SET_USER_BALANCE';
export const SET_USER_REGENERATION = 'SET_USER_REGENERATION';